Mx 14120 esdt supply updates
multiversx/mx-chain-proxy-go pull request #384
Opened 2023-05-02 13:51 UTC by bogdan-rosianu

update esdt supplies endpoint - treat the case when the supply of a token is recomputed

2023-05-02 14:30 UTC, iulianpascalau requested changes

2023-05-04 13:41 UTC, iulianpascalau submitted a review, later dismissed

2023-05-05 09:39 UTC, sstanculeanu approved these changes

2023-05-05 09:39 UTC, sstanculeanu commented on .github/workflows/pr-build.yml
>          uses: actions/setup-go@v2
```suggestion
        uses: actions/setup-go@v3
```
on all occurences

2023-05-05 12:47 UTC, bogdan-rosianu commented on process/esdtSupplyProcessor.go
> +	if sourceSupply.RecomputedSupply {
fixed

2023-05-05 12:47 UTC, sstanculeanu approved these changes

2023-05-17 13:38 UTC, gabi-vuls approved these changes
System test passed

2023-05-17 14:03 UTC, iulianpascalau approved these changes

2023-05-17 14:03 UTC, merged